#!/bin/bash

CP_BACKUP=--backup=numbered
if [[ $1 = "--clean" || $1 = '-c' ]]; then
  unset CP_BACKUP
else
  echo '[Info]: backup of previous config will be created'
  echo '[Hint]: use --clean (or -c) option for suppress backup'
fi

# define package files
files=(
  zshrc
  completions
  prompt
  keyboard
  aliases
  subroutines
  helpers
)

# path to install
ZSH_CONFIG_PATH=/etc/zsh/

# install files
for file in ${files[@]}; do
  cp $CP_BACKUP ./$file $ZSH_CONFIG_PATH
  [[ $? -ne 0 ]] && echo "[Error]: can't copy file $file to $ZSH_CONFIG_PATH" && exit 1
done

echo "[Success]: installation complete"

# we work inside current zsh
if [[ -n $ZSH_VERSION ]]; then
  # reload config
  . /etc/zsh/zshrc && echo "[Success]: config reloaded"
else
  echo "[Hint]: run '. ./install' for reload config automatically"
  echo "[Hint]: use 'zcp-reload' for reload zsh config"
fi

# cleanups
unset CP_BACKUP ZSH_CONFIG_PATH
