#!/bin/bash

# define package files
files=(
  zshrc
  completions
  prompt
  keyboard
  aliases
  subroutines
  helpers
)

# path to install
ZSH_CONFIG_PATH=/etc/zsh/

# install files
for file in ${files[@]}; do
  cp --backup=numbered ./$file $ZSH_CONFIG_PATH
  [[ $? -ne 0 ]] && echo "[Error]: can't copy file $file to $ZSH_CONFIG_PATH" && exit 1
done

echo "[Success]: installation complete"

# we work inside current zsh
if [[ -n $ZSH_VERSION ]]; then
  # reload config
  . /etc/zsh/zshrc && echo "[Success]: config reloaded"
else
  echo "[Hint]: run '. ./install' for reload config automatically"
  echo "[Hint]: run 'zcp-reload' for reload zsh config"
fi

